import * as FS from 'node:fs';
import * as OS from 'node:os';
import * as PATH from 'node:path';
import * as ZLIB from 'node:zlib';
import { spawnSync, type SpawnSyncReturns } from 'node:child_process';
import { packageRoot } from '../src/files.ts';
import { createBundle, fileSigner } from '../src/api.ts';
import type { Console as CliConsole } from '../src/cli.ts';

// Shared fixtures. Every suite signs against the repository's own test PKI in
// certs/, which is generated by certs/gen.sh and is trusted by nothing.

export const ROOT = packageRoot();
export const CERTS = PATH.join(ROOT, 'certs');
export const ROOT_PEM = PATH.join(CERTS, 'root.pem');
export const LEAF_KEY = PATH.join(CERTS, 'leaf.key');
export const CHAIN_PEM = PATH.join(CERTS, 'chain.pem');
export const SHELL_BASE = PATH.join(ROOT, 'shell-base');
export const MAIN = PATH.join(ROOT, 'dist', 'main.js');
export const REGISTER = PATH.join(ROOT, 'dist', 'register.js');

export const key = FS.readFileSync(LEAF_KEY);
export const chain = FS.readFileSync(CHAIN_PEM, 'utf-8');
export const rootPem = FS.readFileSync(ROOT_PEM, 'utf-8');

/** A signer against the test PKI. */
export function testSigner(signAlg = 'sha256') {
    return fileSigner({ key: LEAF_KEY, chain: CHAIN_PEM, signAlg });
}

/**
 * A small multi-file application, so mounting has to resolve a bare entry
 * point, a sibling import and one in a subdirectory through the provider.
 */
export const APP: Record<string, string> = {
    'package.json': '{ "name": "demo", "type": "module", "main": "index.js" }',
    'index.js': [
        "import { greeting } from './greet.js';",
        "import { tag } from './sub/tag.js';",
        'console.log(`${greeting} ${tag} ${process.argv.slice(2).join(",")}`);',
    ].join('\n'),
    'greet.js': "export const greeting = 'hello from a signed bundle';",
    'sub/tag.js': "export const tag = '[sub]';",
};

/** A temporary directory, removed when the suite ends. */
export function scratch(label: string): string {
    return FS.mkdtempSync(PATH.join(OS.tmpdir(), `bundle-${label}-`));
}

/** Writes `files` into a fresh directory under `dir` and returns its path. */
export function tree(dir: string, files: Record<string, string> = APP, name = 'app'): string {
    const source = PATH.join(dir, name);
    for (const [file, content] of Object.entries(files)) {
        const path = PATH.join(source, file);
        FS.mkdirSync(PATH.dirname(path), { recursive: true });
        FS.writeFileSync(path, content);
    }
    return source;
}

/** An archive over `files`, signed against the test PKI unless told otherwise. */
export async function build(source: string, output: string, {
    signed = true, files = Object.keys(APP), prefix,
}: { signed?: boolean; files?: string[]; prefix?: string } = {}): Promise<string> {
    await createBundle({
        base: source, files, output, prefix,
        key: signed ? key : undefined,
        chain: signed ? chain : undefined,
    });
    return output;
}

/** A plain ZIP carrying none of this package's metadata. */
export async function plainZip(source: string, output: string, files = Object.keys(APP)): Promise<string> {
    const entries: ZLIB.ZipEntry[] = [];
    for (const name of files) {
        entries.push(await ZLIB.ZipEntry.create(name, FS.readFileSync(PATH.join(source, name))));
    }
    const chunks: Buffer[] = [];
    for await (const chunk of ZLIB.createZipArchive(entries)) chunks.push(chunk);
    FS.writeFileSync(output, Buffer.concat(chunks));
    return output;
}

/** Runs `target` the way a mount does, with the verifying provider preloaded. */
export function mount(target: string, { roots = [ROOT_PEM], args = [], allowUntrusted = false }: {
    roots?: string[]; args?: string[]; allowUntrusted?: boolean;
} = {}): SpawnSyncReturns<string> {
    const env = { ...process.env };
    delete env['BUNDLE_ROOTS'];
    delete env['BUNDLE_ALLOW_UNTRUSTED'];
    if (roots.length) env['BUNDLE_ROOTS'] = roots.join(PATH.delimiter);
    if (allowUntrusted) env['BUNDLE_ALLOW_UNTRUSTED'] = '1';
    return spawnSync(process.execPath,
        ['--no-warnings', '--experimental-vfs', '-r', REGISTER, '--vfs-load', '--vfs-mount', target, '--', ...args],
        { encoding: 'utf-8', env });
}

/** Runs the built CLI as a subprocess. */
export function cli(args: string[], env: NodeJS.ProcessEnv = {}): SpawnSyncReturns<string> {
    return spawnSync(process.execPath, ['--no-warnings', '--experimental-vfs', MAIN, ...args],
        { encoding: 'utf-8', env: { ...process.env, ...env } });
}

/** A `Console` that collects what a command printed, for in-process CLI tests. */
export function collector(): CliConsole & { stdout: string[]; stderr: string[] } {
    const stdout: string[] = [];
    const stderr: string[] = [];
    return { stdout, stderr, out: (line) => { stdout.push(line); }, err: (line) => { stderr.push(line); } };
}

/**
 * The EOCD comment of `file`. The record is the last thing in the file and its
 * comment runs to EOF, so both are a fixed offset from the end.
 */
export function comment(file: string): string {
    const bytes = FS.readFileSync(file);
    return bytes.subarray(bytes.length - commentLength(bytes)).toString('ascii');
}

export function commentLength(bytes: Buffer): number {
    for (let pos = bytes.length - 22; pos >= 0; pos--) {
        if (bytes.readUInt32LE(pos) !== 0x06054b50) continue;
        if (pos + 22 + bytes.readUInt16LE(pos + 20) !== bytes.length) continue;
        return bytes.readUInt16LE(pos + 20);
    }
    throw new Error('no end of central directory record found');
}

/** Replaces the EOCD comment of `file` with `marker`, leaving the rest intact. */
export function rewriteComment(file: string, marker: string): void {
    const bytes = FS.readFileSync(file);
    const forged = Buffer.from(marker, 'ascii');
    const head = bytes.subarray(0, bytes.length - commentLength(bytes) - 2);
    const length = Buffer.alloc(2);
    length.writeUInt16LE(forged.length, 0);
    FS.writeFileSync(file, Buffer.concat([head, length, forged]));
}
